### ISSUE TITLE
Help with Hello World app

### ISSUE THREAD

**Issue by ufmemo** [ninjaframework/ninja-appengine#16]
We're in the process of evaluating lightweight Java web frameworks for Java & GAE. The Ninja framework documentation indicates this is a great fit. I have spent three full days trying to get a basic hello world styled app to run on GAE but haven't been able to get past this issue.

Uncaught exception from servlet
java.lang.ExceptionInInitializerError
at org.slf4j.LoggerFactory.reportMultipleBindingAmbiguity(LoggerFactory.java:259)
at org.slf4j.LoggerFactory.bind(LoggerFactory.java:139)
at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
at ninja.utils.NinjaPropertiesImpl.(NinjaPropertiesImpl.java:40)
at ninja.servlet.NinjaServletListener.getInjector(NinjaServletListener.java:103)

I've tried to remove every reference to slf4j but no luck. Any help would be much appreciated. I've used the maven archetype for the GAE Blog application, created a basic GAE app and then imported all the Ninja dependencies, both yield the same frustrating results.

Thanks for the help in advance.

**Comment by raphaelbauer** [comment]
Hey ufmemo,

the GAE is a bit of a diva sometimes. The latest GAE introduced a bug?
which results in the wrong dependencies being sent via the upload goal to
GAE.
The solution to your problem is to exclude the log stuff from the test
utils like so:

        <dependency>

            <groupId>org.ninjaframework</groupId>

            <artifactId>ninja-test-utilities</artifactId>

            <version>${ninja.version}</version>

            <scope>test</scope>

              <exclusions>

                <exclusion>

                    <artifactId>logback-classic</artifactId>

                    <groupId>ch.qos.logback</groupId>

                </exclusion>

            </exclusions>

        </dependency>


Cheers,


Raphael
